import React from 'react';
import './App.css';
import {F1Info} from "./F1Info";
import {InformationTemplate} from "./interfaces";
import {CountClicks} from "./CountClicks";
import {ComplexCountClicks} from "./ComplexCountClicks";
import { BrowserRouter as Router, Routes, Route} from "react-router-dom";
import {NotFound} from "./NotFound";
import RoundDetails from "./RoundDetails";

function App() {

    const logo: string = 'https://assets.stickpng.com/thumbs/61fc02163cf0e70004222072.png'
    const title: string = 'THE PINNACLE OF MOTORSPORT';
    const firstParagraph: string = 'Formula 1 is the highest class of international racing for open-wheel single-seater formula racing cars sanctioned by the FIA.\n';
    const secondParagraph: string = 'Formula One cars are the fastest regulated road-course racing cars in the world,\n' +
        '            owing to very high cornering speeds achieved through generating large amounts of\n' +
        '            aerodynamic downforce. Much of this downforce is generated by front and rear wings,\n' +
        '            which have the side effect of causing severe turbulence behind each car.\n' +
        '            The turbulence reduces the downforce generated by the cars following directly behind,\n' +
        '            making it hard to overtake.\n ' +
        '            Choose a season from the list below to see more information. Click a round to get more info.\n'  ;

    const infoTemplate: InformationTemplate = {
        title,
        firstParagraph,
        secondParagraph,
        logo
    }

    return (
        <div className="App App-header">
            <Router>
                <Routes>
                    <Route path="/counter" element={<CountClicks/>} />
                    <Route path="/complex-counter" element={<ComplexCountClicks />}/>
                    <Route path="/" element={<F1Info {...infoTemplate} />} />
                    <Route path="/:season/rounds/:roundId" element={<RoundDetails />} />
                    <Route path="*" element={<NotFound />} />
                </Routes>
            </Router>
        </div>
    )
}

export default App;
